### ISSUE TITLE
Install process

### ISSUE THREAD

**Issue by craigmillard86** [invisiblesushi/ESP32-BLE-SNES-controller#1]
Great project! 
How is the PCB fitted into the controller? Do you have an images?

**Comment by invisiblesushi** [comment]
I attached some images, keep in mind the PCB design is still work in progress. And is a tight fit, so recommend to order 0.8mm thickness from JLCPCB.
PCB is also desinged for a clone SNES controller aka 16 bit Super Game Controller.

![IMG_20230305_105147.jpg](https://user-images.githubusercontent.com/6609276/222953479-31a98ced-c43b-47bf-9ca0-1695d2fa9b0a.jpg)

![IMG_20230305_105043424.jpg](https://user-images.githubusercontent.com/6609276/222953480-9553f056-2ff7-449a-bc07-39c36fd916f4.jpg)

![IMG_20230305_105123.jpg](https://user-images.githubusercontent.com/6609276/222953481-98943d56-810e-44c0-8b3f-c3dea9a46272.jpg)

![IMG_20230305_105156.jpg](https://user-images.githubusercontent.com/6609276/222953482-5c03c5eb-6ca8-48b9-bd68-e61fd9dccd60.jpg)
