### ISSUE TITLE
Battery life

### ISSUE THREAD

**Issue by bennettopaul** [invisiblesushi/ESP32-BLE-SNES-controller#2]
I was considering building something similar to this (barrel jack from the cable connector instead of USB C). Could you tell me what kind of battery life you get out of it?

**Comment by invisiblesushi** [comment]
Hi @bennettopaul , I have not yet testet the batterylife of this project yet.

But in theory if we assume ESP32 consumes around 100-130mA when bluetooth is active and transmitting. The 300mAh 601235 Lithium battery should last 2-3 hours in best case senario. But the battery life would be less cause when the voltage drops to much it will trigger an "Brownout detector was triggered" error and be stuck in a boot loop.

[https://electronics.stackexchange.com/questions/615765/why-is-esp32-ble-so-power-hungry#:~:text=The%20ESP32%20consumes%20around%20100,BLE%20is%20active%20and%20transmitting.](url)

**Comment by bennettopaul** [comment]
Ah, OK. I might go with something like a NRF chip then.
